version: '2'
services:
  mysql:
    image: vaibhavjain882/mysql_test
    ports:
       - 3306:3306
  
  java_application_server1:
    image: vaibhavjain882/java_test_application
    ports: 
       - 8081:8080
    links:
       - mysql:mysql
    depends_on:
       - mysql

  java_application_server2:
    image: vaibhavjain882/java_test_application        
    ports:
       - 8082:8080
    links:
       - mysql:mysql
    depends_on:
       - mysql
 
  loadbalancer:
    image: vaibhavjain882/loadbalancer_nginx
    ports:
       - 85:80
    depends_on:
       - mysql
       - java_application_server1
       - java_application_server2
